app:
  name: "web_app"
  mode: "dev"
  port: 8080

log:
  level: "debug"
  filename: "./log/web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 10

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  database: "keyshare"
  maxOpenConns: 200
  maxIdleConns: 50

redis: 
  host: "localhost"
  port: 6379 
  password: "123456"
  db: 0
  poolSize: 100